import { useState } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";
import { Plus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
  DialogTrigger,
} from "@/components/ui/dialog";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";

interface Props {
  clientId?: string | null;
  companyId?: string | null;
}

/**
 * Add a single service to an existing client/company. Delegates to the add_service_to_client RPC,
 * which creates (or reuses) the engagement and materialises the job + deadlines for the chosen
 * period via the same engine as the quote path. The accountant picks the period explicitly (year
 * end, tax year, VAT quarter, pay period, …) — captured here as period start/end + a label.
 */
export function AddServiceDialog({ clientId, companyId }: Props) {
  const qc = useQueryClient();
  const [open, setOpen] = useState(false);
  const [serviceId, setServiceId] = useState("");
  const [periodStart, setPeriodStart] = useState("");
  const [periodEnd, setPeriodEnd] = useState("");
  const [label, setLabel] = useState("");

  const services = useQuery({
    queryKey: ["services-catalog-active"],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("services_catalog")
        .select("id, name, code")
        .eq("active", true)
        .order("name");
      if (error) throw error;
      return (data ?? []) as { id: string; name: string; code: string }[];
    },
    enabled: open,
  });

  const reset = () => {
    setServiceId("");
    setPeriodStart("");
    setPeriodEnd("");
    setLabel("");
  };

  const add = useMutation({
    mutationFn: async () => {
      // Cast: this RPC is new; the generated Supabase types are regenerated by Lovable on apply.
      const { data, error } = await (supabase.rpc as unknown as (
        fn: string,
        args: Record<string, unknown>,
      ) => Promise<{ data: unknown; error: { message: string } | null }>)("add_service_to_client", {
        p_client_id: clientId ?? null,
        p_company_id: companyId ?? null,
        p_service_id: serviceId,
        p_period_start: periodStart,
        p_period_end: periodEnd,
        p_period_label: label.trim(),
      });
      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      toast.success("Service added");
      qc.invalidateQueries({ queryKey: ["client-engagements"] });
      qc.invalidateQueries({ queryKey: ["company-engagements"] });
      setOpen(false);
      reset();
    },
    onError: (e: Error) => toast.error(e.message || "Failed to add service"),
  });

  const canSubmit = !!serviceId && !!periodStart && !!periodEnd && !!label.trim();

  return (
    <Dialog open={open} onOpenChange={(o) => { setOpen(o); if (!o) reset(); }}>
      <DialogTrigger asChild>
        <Button size="sm">
          <Plus className="h-4 w-4 mr-2" />
          Add Service
        </Button>
      </DialogTrigger>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>Add a service</DialogTitle>
        </DialogHeader>
        <div className="space-y-4">
          <div className="space-y-1">
            <Label>Service</Label>
            <Select value={serviceId} onValueChange={setServiceId}>
              <SelectTrigger>
                <SelectValue placeholder={services.isLoading ? "Loading…" : "Select a service…"} />
              </SelectTrigger>
              <SelectContent>
                {(services.data ?? []).map((s) => (
                  <SelectItem key={s.id} value={s.id}>{s.name}</SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
          <div className="grid grid-cols-2 gap-3">
            <div className="space-y-1">
              <Label>Period start</Label>
              <Input type="date" value={periodStart} onChange={(e) => setPeriodStart(e.target.value)} />
            </div>
            <div className="space-y-1">
              <Label>Period end</Label>
              <Input
                type="date"
                value={periodEnd}
                onChange={(e) => {
                  setPeriodEnd(e.target.value);
                  if (!label && e.target.value) setLabel(e.target.value.slice(0, 4));
                }}
              />
            </div>
          </div>
          <div className="space-y-1">
            <Label>Period label</Label>
            <Input
              placeholder="e.g. 2025/26, YE 31 Mar 2026, Q1 2026"
              value={label}
              onChange={(e) => setLabel(e.target.value)}
            />
            <p className="text-xs text-muted-foreground">
              The period this service covers — the year end, tax year, VAT quarter or pay period.
            </p>
          </div>
        </div>
        <DialogFooter>
          <Button variant="outline" onClick={() => setOpen(false)}>Cancel</Button>
          <Button onClick={() => add.mutate()} disabled={!canSubmit || add.isPending}>
            {add.isPending ? "Adding…" : "Add service"}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
