// Auto-generated by scripts/stamp-release.ts. Do not edit by hand.
// Committed with unstamped placeholder values so the module compiles today;
// scripts/stamp-release.ts overwrites this file before a controlled release.
import type { ReleaseIdentity } from "../_shared/release-version.ts";

export const RELEASE: ReleaseIdentity = {
  RELEASE_SHA: "unstamped",
  RELEASE_ID: "unstamped",
  ARTIFACT_CHECKSUM: "unstamped",
  RELEASE_BUILD_AT: "1970-01-01T00:00:00Z",
};