#!/usr/bin/env bun
// Write a stamped VERSION.ts for an edge function.
//
// Usage:
//   bun scripts/stamp-release.ts --function <name> --sha <git_sha> --release-id <id> [--dry-run]

import { writeFileSync, existsSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import { computeChecksum } from "./release-checksum.ts";

function arg(name: string): string | undefined {
  const i = process.argv.indexOf(`--${name}`);
  return i === -1 ? undefined : process.argv[i + 1];
}
function flag(name: string): boolean {
  return process.argv.includes(`--${name}`);
}

function main() {
  const fn = arg("function");
  const sha = arg("sha");
  const releaseId = arg("release-id");
  const dryRun = flag("dry-run");
  const buildAt = arg("build-at") ?? new Date().toISOString();
  if (!fn || !sha || !releaseId) {
    console.error("usage: bun scripts/stamp-release.ts --function <name> --sha <git_sha> --release-id <id> [--build-at <iso>] [--dry-run]");
    process.exit(2);
  }
  const dir = join("supabase", "functions", fn);
  if (!existsSync(dir)) {
    console.error(`no such function: ${dir}`);
    process.exit(2);
  }
  const { checksum } = computeChecksum(dir);
  const contents = `// Auto-generated by scripts/stamp-release.ts. Do not edit by hand.\n` +
    `import type { ReleaseIdentity } from "../_shared/release-version.ts";\n\n` +
    `export const RELEASE: ReleaseIdentity = {\n` +
    `  RELEASE_SHA: ${JSON.stringify(sha)},\n` +
    `  RELEASE_ID: ${JSON.stringify(releaseId)},\n` +
    `  ARTIFACT_CHECKSUM: ${JSON.stringify(checksum)},\n` +
    `  RELEASE_BUILD_AT: ${JSON.stringify(buildAt)},\n` +
    `};\n`;
  const target = join(dir, "VERSION.ts");
  if (dryRun) {
    console.log(`# would write ${target}`);
    console.log(contents);
    return;
  }
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  writeFileSync(target, contents);
  console.log(`wrote ${target} (checksum=${checksum})`);
}

if (import.meta.main) main();