// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/list-clients.ts
import { createClient } from "npm:@supabase/supabase-js@^2.84.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^3.25.0";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_clients_default = defineTool({
  name: "list_clients",
  title: "List clients",
  description: "List clients in the signed-in user's organisation. Returns id, name, email, status and type.",
  inputSchema: {
    search: z.string().trim().max(200).optional().describe("Optional case-insensitive substring to match against first/last name or email."),
    limit: z.number().int().min(1).max(100).default(25).describe("Max rows to return (1-100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    let query = sb.from("clients").select("id, first_name, last_name, email, status, client_type").order("updated_at", { ascending: false }).limit(limit);
    if (search) {
      const s = `%${search}%`;
      query = query.or(`first_name.ilike.${s},last_name.ilike.${s},email.ilike.${s}`);
    }
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { clients: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-jobs.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.84.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^3.25.0";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_jobs_default = defineTool2({
  name: "list_jobs",
  title: "List jobs",
  description: "List active jobs in the signed-in user's organisation, most recently updated first.",
  inputSchema: {
    status: z2.string().trim().max(64).optional().describe("Optional exact status filter (e.g. 'in_progress', 'completed')."),
    limit: z2.number().int().min(1).max(100).default(25).describe("Max rows to return (1-100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser2(ctx);
    let query = sb.from("jobs").select(
      "id, job_name, service_type, status, priority, filing_deadline, period_label, client_id, company_id, updated_at"
    ).order("updated_at", { ascending: false }).limit(limit);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { jobs: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-deadlines.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.84.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^3.25.0";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_deadlines_default = defineTool3({
  name: "list_upcoming_deadlines",
  title: "List upcoming deadlines",
  description: "List upcoming (not-yet-filed) statutory and internal deadlines in the signed-in user's organisation, soonest first.",
  inputSchema: {
    within_days: z3.number().int().min(1).max(365).default(60).describe("Only include deadlines due within this many days from today."),
    limit: z3.number().int().min(1).max(200).default(50).describe("Max rows to return (1-200).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ within_days, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser3(ctx);
    const now = /* @__PURE__ */ new Date();
    const until = new Date(now.getTime() + within_days * 864e5);
    const { data, error } = await sb.from("deadlines").select(
      "id, name, deadline_type, filing_body, due_date, status, client_id, company_id, service_code"
    ).is("filed_at", null).gte("due_date", now.toISOString().slice(0, 10)).lte("due_date", until.toISOString().slice(0, 10)).order("due_date", { ascending: true }).limit(limit);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { deadlines: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "moxpdejnucjjcplleefn";
var mcp_default = defineMcp({
  name: "accountancyos-mcp",
  title: "AccountancyOS",
  version: "0.1.0",
  instructions: "Read-only tools for an AccountancyOS practice. Use list_clients to look up clients, list_jobs to inspect work in progress, and list_upcoming_deadlines to see what is due. All calls act as the signed-in user and respect their organisation permissions.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_clients_default, list_jobs_default, list_deadlines_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
