
-- Make organization_id nullable for system templates
ALTER TABLE public.message_templates ALTER COLUMN organization_id DROP NOT NULL;

-- Seed system message templates
INSERT INTO public.message_templates (organization_id, name, subject, body, channel, key, is_system, variables_schema) VALUES
  (NULL, 'Proposal Follow-Up 1', 'Following up on our proposal', '<p>Hi {{client.preferred_name}},</p><p>Just checking in regarding the proposal we sent across.</p><p>Best regards,<br/>{{practice.name}}</p>', 'email', 'CRM_PROPOSAL_FOLLOWUP_1', true, '{"client.preferred_name": "string", "practice.name": "string"}'::jsonb),
  (NULL, 'Proposal Follow-Up 2', 'Checking in — proposal', '<p>Hi {{client.preferred_name}},</p><p>Wanted to follow up once more on our proposal.</p><p>Best regards,<br/>{{practice.name}}</p>', 'email', 'CRM_PROPOSAL_FOLLOWUP_2', true, '{"client.preferred_name": "string", "practice.name": "string"}'::jsonb),
  (NULL, 'Welcome Email', 'Welcome to {{practice.name}}', '<p>Dear {{client.preferred_name}},</p><p>Welcome aboard! You''ll receive a questionnaire shortly.</p><p>Best regards,<br/>{{practice.name}}</p>', 'email', 'ONBOARDING_WELCOME', true, '{"client.preferred_name": "string", "practice.name": "string"}'::jsonb),
  (NULL, 'Onboarding Next Steps', 'Next steps for your account', '<p>Hi {{client.preferred_name}},</p><p>Thank you for completing your onboarding questionnaire. We''ll be in touch shortly.</p><p>Best regards,<br/>{{practice.name}}</p>', 'email', 'ONBOARDING_NEXT_STEPS', true, '{"client.preferred_name": "string", "practice.name": "string"}'::jsonb),
  (NULL, 'SA Records Request', 'Tax return records needed — {{period.label}}', '<p>Dear {{client.preferred_name}},</p><p>We''re preparing your SA return for {{period.label}}. Please provide records.</p><p>Deadline: {{deadline.date}}</p><p>Best regards,<br/>{{practice.name}}</p>', 'email', 'SA_RECORDS_REQUEST', true, '{"client.preferred_name": "string", "period.label": "string", "deadline.date": "string", "practice.name": "string"}'::jsonb),
  (NULL, 'SA SLA Breach', 'Overdue: SA return for {{client.preferred_name}}', '<p>SA return for {{client.preferred_name}} ({{period.label}}) exceeded 14-day SLA.</p>', 'email', 'SA_SLA_BREACH', true, '{"client.preferred_name": "string", "period.label": "string"}'::jsonb),
  (NULL, 'MTD Quarterly Records Request', 'Quarterly update records — {{period.label}}', '<p>Dear {{client.preferred_name}},</p><p>MTD quarterly for {{period.label}} is due. Deadline: {{deadline.date}}</p><p>Best regards,<br/>{{practice.name}}</p>', 'email', 'MTD_QUARTERLY_RECORDS_REQUEST', true, '{"client.preferred_name": "string", "period.label": "string", "deadline.date": "string", "practice.name": "string"}'::jsonb),
  (NULL, 'MTD EOPS Records Request', 'End of year records — {{period.label}}', '<p>Dear {{client.preferred_name}},</p><p>MTD EOPS for {{period.label}} is due. Deadline: {{deadline.date}}</p><p>Best regards,<br/>{{practice.name}}</p>', 'email', 'MTD_EOPS_RECORDS_REQUEST', true, '{"client.preferred_name": "string", "period.label": "string", "deadline.date": "string", "practice.name": "string"}'::jsonb),
  (NULL, 'Ltd Records Request', 'Year-end records — {{company.company_name}}', '<p>Dear {{client.preferred_name}},</p><p>Preparing accounts for {{company.company_name}} {{period.label}}.</p><p>Best regards,<br/>{{practice.name}}</p>', 'email', 'LTD_RECORDS_REQUEST', true, '{"client.preferred_name": "string", "company.company_name": "string", "period.label": "string", "practice.name": "string"}'::jsonb),
  (NULL, 'Ltd SLA Breach', 'Overdue: Accounts for {{company.company_name}}', '<p>Accounts for {{company.company_name}} ({{period.label}}) exceeded 21-day SLA.</p>', 'email', 'LTD_SLA_BREACH', true, '{"company.company_name": "string", "period.label": "string"}'::jsonb),
  (NULL, 'CS01 Review Request', 'Confirmation statement — {{company.company_name}}', '<p>Dear {{client.preferred_name}},</p><p>Please review the confirmation statement for {{company.company_name}}.</p><p>Best regards,<br/>{{practice.name}}</p>', 'email', 'CS01_REVIEW_REQUEST', true, '{"client.preferred_name": "string", "company.company_name": "string", "practice.name": "string"}'::jsonb),
  (NULL, 'VAT Records Request', 'VAT return records — {{period.label}}', '<p>Dear {{client.preferred_name}},</p><p>VAT return for {{period.label}} is due. Deadline: {{deadline.date}}</p><p>Best regards,<br/>{{practice.name}}</p>', 'email', 'VAT_RECORDS_REQUEST', true, '{"client.preferred_name": "string", "period.label": "string", "deadline.date": "string", "practice.name": "string"}'::jsonb),
  (NULL, 'VAT SLA Breach', 'Overdue: VAT return for {{company.company_name}}', '<p>VAT return for {{company.company_name}} ({{period.label}}) exceeded 7-day SLA.</p>', 'email', 'VAT_SLA_BREACH', true, '{"company.company_name": "string", "period.label": "string"}'::jsonb),
  (NULL, 'Payroll Changes Request', 'Payroll changes — {{period.label}}', '<p>Dear {{client.preferred_name}},</p><p>Processing payroll for {{company.company_name}} {{period.label}}. Advise changes by {{deadline.date}}.</p><p>Best regards,<br/>{{practice.name}}</p>', 'email', 'PAYROLL_CHANGES_REQUEST', true, '{"client.preferred_name": "string", "company.company_name": "string", "period.label": "string", "deadline.date": "string", "practice.name": "string"}'::jsonb),
  (NULL, 'P60 Distribution', 'P60s ready — {{period.label}}', '<p>Dear {{client.preferred_name}},</p><p>P60s for {{company.company_name}} {{period.label}} are available.</p><p>Best regards,<br/>{{practice.name}}</p>', 'email', 'P60_DISTRIBUTION', true, '{"client.preferred_name": "string", "company.company_name": "string", "period.label": "string", "practice.name": "string"}'::jsonb),
  (NULL, 'CIS Details Request', 'CIS return details — {{period.label}}', '<p>Dear {{client.preferred_name}},</p><p>Need subcontractor details for CIS {{period.label}}. By {{deadline.date}}.</p><p>Best regards,<br/>{{practice.name}}</p>', 'email', 'CIS_SUBCONTRACTOR_DETAILS_REQUEST', true, '{"client.preferred_name": "string", "period.label": "string", "deadline.date": "string", "practice.name": "string"}'::jsonb),
  (NULL, 'CGT Records Request', 'CGT 60-day report — records needed', '<p>Dear {{client.preferred_name}},</p><p>Please provide completion statement for CGT report. Deadline: {{deadline.date}}</p><p>Best regards,<br/>{{practice.name}}</p>', 'email', 'CGT_RECORDS_REQUEST', true, '{"client.preferred_name": "string", "deadline.date": "string", "practice.name": "string"}'::jsonb),
  (NULL, 'CGT SLA Breach', 'Overdue: CGT report for {{client.preferred_name}}', '<p>CGT 60-day report for {{client.preferred_name}} exceeded 7-day SLA.</p>', 'email', 'CGT_SLA_BREACH', true, '{"client.preferred_name": "string"}'::jsonb),
  (NULL, 'Charity Records Request', 'Annual return records — {{company.company_name}}', '<p>Dear {{client.preferred_name}},</p><p>Preparing annual return for {{company.company_name}} {{period.label}}. Deadline: {{deadline.date}}</p><p>Best regards,<br/>{{practice.name}}</p>', 'email', 'CHARITY_RECORDS_REQUEST', true, '{"client.preferred_name": "string", "company.company_name": "string", "period.label": "string", "deadline.date": "string", "practice.name": "string"}'::jsonb),
  (NULL, 'SLA Breach — 24h', 'Client message awaiting response (24h)', '<p>Message from {{client.preferred_name}} waiting over 24 hours. Please respond.</p>', 'email', 'SLA_BREACH_24H', true, '{"client.preferred_name": "string"}'::jsonb),
  (NULL, 'Deadline Reminder — 30 Days', 'Reminder: {{deadline.type}} in 30 days', '<p>Dear {{client.preferred_name}},</p><p>{{deadline.type}} for {{period.label}} in 30 days ({{deadline.date}}).</p><p>Best regards,<br/>{{practice.name}}</p>', 'email', 'DEADLINE_REMINDER_30D', true, '{"client.preferred_name": "string", "deadline.type": "string", "period.label": "string", "deadline.date": "string", "practice.name": "string"}'::jsonb),
  (NULL, 'Deadline Reminder — 14 Days', 'Reminder: {{deadline.type}} in 14 days', '<p>Dear {{client.preferred_name}},</p><p>{{deadline.type}} for {{period.label}} in 14 days ({{deadline.date}}).</p><p>Best regards,<br/>{{practice.name}}</p>', 'email', 'DEADLINE_REMINDER_14D', true, '{"client.preferred_name": "string", "deadline.type": "string", "period.label": "string", "deadline.date": "string", "practice.name": "string"}'::jsonb),
  (NULL, 'Deadline Reminder — 7 Days', 'URGENT: {{deadline.type}} in 7 days', '<p>Dear {{client.preferred_name}},</p><p><strong>Urgent:</strong> {{deadline.type}} for {{period.label}} in 7 days ({{deadline.date}}).</p><p>Best regards,<br/>{{practice.name}}</p>', 'email', 'DEADLINE_REMINDER_7D', true, '{"client.preferred_name": "string", "deadline.type": "string", "period.label": "string", "deadline.date": "string", "practice.name": "string"}'::jsonb),
  (NULL, 'Filing Accepted', '{{filing.type}} accepted by {{filing.authority}}', '<p>Dear {{client.preferred_name}},</p><p>{{filing.type}} for {{period.label}} accepted. Ref: {{filing.reference}}</p><p>Best regards,<br/>{{practice.name}}</p>', 'email', 'FILING_ACCEPTED_CONFIRMATION', true, '{"client.preferred_name": "string", "filing.type": "string", "period.label": "string", "filing.authority": "string", "filing.reference": "string", "practice.name": "string"}'::jsonb),
  (NULL, 'Records Received', 'Records received — thank you', '<p>Dear {{client.preferred_name}},</p><p>Thank you for providing records for {{period.label}}.</p><p>Best regards,<br/>{{practice.name}}</p>', 'email', 'RECORDS_RECEIVED_ACK', true, '{"client.preferred_name": "string", "period.label": "string", "practice.name": "string"}'::jsonb),
  (NULL, 'Job Completed', '{{job.name}} — completed', '<p>Dear {{client.preferred_name}},</p><p>{{job.name}} for {{period.label}} has been completed.</p><p>Best regards,<br/>{{practice.name}}</p>', 'email', 'JOB_COMPLETED_NOTIFICATION', true, '{"client.preferred_name": "string", "job.name": "string", "period.label": "string", "practice.name": "string"}'::jsonb);
